name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Process
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Make script executable
        run: chmod +x ./script.sh

      - name: Run build script
        run: ./script.sh
