name: Hello World Workflow

on: ["push"]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A test for custom YAML
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use custom action
        id: hello
        uses: sayam-em/GitHub-Actions-day-1@v1.0.0
        with:
          name: "Sayam"

      - name: Output greeting
        run: echo "yo, ${{ steps.hello.outputs.greeting }}"
