on: ["push"]

jobs:
    my-job:
        runs-on: ubuntu-latest
        name: a test for custom yaml
        steps:
          - name: step 1
            id: hello
            uses: sayam-em/GitHub-Actions-day-1@0.0.1
            with:
              name: "Sayam"
          - name: output
            run: echo "yo, ${{steps.hello.outputs.greetings}}"

        