name: Use API Key

on:
  push:
    branches:
      - main

jobs:
  make-api-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use API Key
        run: |
          echo "Using My Secret 1: ${{ secrets.MY_SECRET }}"
          echo "Using My Secret 2 $MY_SECRET"
          echo "Using My Secret 3 ${{ secrets.MY_SECRET }}"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}