name: "depends"

on: ["push"]

jobs:
  job1:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: "step1"
        run: echo "World"
  job2: 
    runs-on: ubuntu-latest
    steps:
      - name: "step2"
        run: echo "Hello"